version: "3"
name: vetoo
services:
  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
      - database
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/

  backend:
    build: ./api
    depends_on:
      - database
    volumes:
      - ./api/src:/app/src
      - ./.env:/app/.env
    ports:
      - "3001:80"

  frontend:
    build: ./client
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    ports:
      - "3000:3000"

  database:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    env_file:
      - .env
