CREATE USER 'webuser'@'%' IDENTIFIED BY '}c@63usWz5_XE7';
GRANT SELECT, INSERT, UPDATE, DELETE ON vetoo.* TO 'webuser'@'%';

CREATE DATABASE IF NOT EXISTS `vetoo`;

USE `vetoo`;

CREATE TABLE IF NOT EXISTS `users` (
    id INT NOT NULL AUTO_INCREMENT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `pets` (
    user_id INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    birthdate DATETIME,
    name VARCHAR(10) NOT NULL,
    type ENUM('d', 'c', 'n') NOT NULL,
    gender ENUM('m', 'f'),
    chip VARCHAR(10),
    picture_url VARCHAR(14),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS `appointments` (
    pet_id INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    meet_at DATETIME NOT NULL,
    title VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (pet_id) REFERENCES pets(id)
);
